# Generated by Django 6.0.6 on 2026-06-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("imports", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "counterparty_raw",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "legal_entity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "store_location_raw",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "city_or_area",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contract_raw",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contract_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("contract_date", models.DateField(blank=True, null=True)),
                (
                    "payment_doc_raw",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_doc_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "period_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_file_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "source_file_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "source_sheet",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("source_row_number", models.IntegerField(blank=True, null=True)),
                (
                    "source_column",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_records",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "payment_date"],
                        name="payments_pa_organiz_a8d68d_idx",
                    ),
                    models.Index(
                        fields=["organization", "legal_entity"],
                        name="payments_pa_organiz_0d2518_idx",
                    ),
                    models.Index(
                        fields=["organization", "contract_number"],
                        name="payments_pa_organiz_dbb08d_idx",
                    ),
                ],
            },
        ),
    ]
