# Generated by Django 6.0.6 on 2026-06-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("imports", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_date", models.DateField(blank=True, null=True)),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[("credit", "Поступление"), ("debit", "Списание")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "counterparty_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "counterparty_inn",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "counterparty_kpp",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "counterparty_account",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "counterparty_bik",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "counterparty_bank_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payment_purpose", models.TextField(blank=True, null=True)),
                (
                    "debtor_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_file_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "source_file_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "source_sheet",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("source_row_number", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transactions",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_transactions",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "operation_date"],
                        name="banking_ban_organiz_ab3cfd_idx",
                    ),
                    models.Index(
                        fields=["organization", "direction"],
                        name="banking_ban_organiz_69b722_idx",
                    ),
                    models.Index(
                        fields=["organization", "counterparty_inn"],
                        name="banking_ban_organiz_46b4a4_idx",
                    ),
                ],
            },
        ),
    ]
