# Generated by Django 6.0.6 on 2026-06-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomenclature_raw", models.CharField(max_length=255, unique=True)),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="общее название"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="актуальность"),
                ),
                (
                    "shelf_life_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="срок годности, дней"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="себестоимость за единицу",
                    ),
                ),
                ("first_sale_date", models.DateField(blank=True, null=True)),
                ("last_sale_date", models.DateField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_name", "nomenclature_raw"],
            },
        ),
    ]
